// Blender bridge -- render an internal scene package to linear RGBA float pixels
#define TINYOBJLOADER_IMPLEMENTATION
#include "tiny_obj_loader.h"
#define STB_IMAGE_IMPLEMENTATION
#include "stb_image.h"

#include "raytracer/render/renderer.h"
#include "raytracer/render/rgba32f.h"
#include "raytracer/scene/scene.h"
#include <algorithm>
#include <cstdlib>
#include <exception>
#include <iostream>
#include <string>

namespace {

struct BridgeArgs {
    std::string scene_path;
    std::string out_float_path;
    int samples_override = -1;
    int max_depth_override = -1;
    RenderOptions render_options;
};

void print_usage(const char* prog) {
    std::cerr << "Usage: " << prog << " --scene <path> --out-float <path> [options]\n"
              << "  --scene <path>       internal scene package generated by the Blender addon\n"
              << "  --out-float <path>   output RGBA32F binary file\n"
              << "  --samples <n>        samples per pixel override\n"
              << "  --max-depth <n>      ray recursion depth override\n"
              << "  --threads <n>        render worker threads\n"
              << "  --direct-only        disable recursive random bounces\n"
              << "  --version            print bridge protocol version\n";
}

bool parse_args(int argc, char* argv[], BridgeArgs& args) {
    for (int i = 1; i < argc; i++) {
        std::string arg = argv[i];
        if (arg == "--scene" && i + 1 < argc) {
            args.scene_path = argv[++i];
        } else if (arg == "--out-float" && i + 1 < argc) {
            args.out_float_path = argv[++i];
        } else if (arg == "--samples" && i + 1 < argc) {
            args.samples_override = std::stoi(argv[++i]);
        } else if (arg == "--max-depth" && i + 1 < argc) {
            args.max_depth_override = std::stoi(argv[++i]);
        } else if (arg == "--threads" && i + 1 < argc) {
            args.render_options.threads = std::stoi(argv[++i]);
            if (args.render_options.threads <= 0) {
                std::cerr << "--threads must be greater than 0\n";
                return false;
            }
        } else if (arg == "--direct-only") {
            args.render_options.direct_only = true;
        } else if (arg == "--version") {
            std::cout << "raytracer-blender-bridge protocol=1\n";
            std::exit(0);
        } else if (arg == "--help" || arg == "-h") {
            print_usage(argv[0]);
            std::exit(0);
        } else {
            std::cerr << "Unknown argument: " << arg << "\n";
            return false;
        }
    }

    if (args.scene_path.empty() || args.out_float_path.empty()) {
        std::cerr << "--scene and --out-float are required\n";
        return false;
    }
    return true;
}

}  // namespace

int main(int argc, char* argv[]) {
    BridgeArgs args;
    if (!parse_args(argc, argv, args)) {
        print_usage(argv[0]);
        return 1;
    }

    Scene scene;
    try {
        load_scene(args.scene_path, scene);
    } catch (const std::exception& e) {
        std::cerr << "ERROR loading scene: " << e.what() << "\n";
        return 1;
    }

    if (args.samples_override > 0) scene.samples = args.samples_override;
    if (args.max_depth_override > 0) scene.max_depth = args.max_depth_override;

    std::cerr << "INFO scene=" << args.scene_path
              << " image=" << scene.width << "x" << scene.height
              << " samples=" << scene.samples
              << " depth=" << scene.max_depth
              << " primitives=" << scene.primitive_count << "\n";

    RenderCallbacks callbacks;
    callbacks.progress = [](double progress) {
        double clamped = std::clamp(progress, 0.0, 1.0);
        std::cerr << "PROGRESS " << clamped << "\n" << std::flush;
    };

    RenderOutput output = render_scene(scene, args.render_options, callbacks);
    if (output.cancelled) {
        std::cerr << "ERROR render cancelled\n";
        return 2;
    }

    try {
        write_rgba32f(args.out_float_path, output);
    } catch (const std::exception& e) {
        std::cerr << "ERROR writing result: " << e.what() << "\n";
        return 1;
    }

    std::cerr << "DONE " << args.out_float_path << "\n";
    return 0;
}
